### ISSUE TITLE
Erlang performance

### ISSUE THREAD

**Issue by silviucpp** [jakubkulhan/hit-server-bench#15]
Almost all apps that needs an builtin http server are using cowboy not the one that you are testing . 

Will be nice to see a test on cowboy https://github.com/ninenines/cowboy

Silviu

**Comment by jakubkulhan** [comment]
Hi. Unfortunately, I don't know Cowboy enough to make code for the benchmark. I'd be happy to accept PR with Cowboy benchmark.

**Comment by baryluk** [comment]
Using non-inets would be nice, but single line change in current server initialization makes the server run 500 times faster.

https://github.com/jakubkulhan/hit-server-bench/pull/18 sent for merging with other minor improvements in code style.

Thanks.
